"""baseline schema

Revision ID: cf95e88e2c79
Revises: 
Create Date: 2026-03-05 18:10:39.002409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf95e88e2c79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('service_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('supplier_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_reviews_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False))
        batch_op.alter_column('due_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_deadlines_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_properties_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_deadlines_due_date'))
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('supplier_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_reviews_tenant_id'))

    op.drop_table('supplier_reviews')
    with op.batch_alter_table('supplier_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_documents_tenant_id'))

    op.drop_table('supplier_documents')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_tenant_id'))

    op.drop_table('suppliers')
    # ### end Alembic commands ###
